services:
  processor-template:
    build:
      context: ../../
      dockerfile: src/docker/processor/Dockerfile
    environment:
      DATABASE_URL: "postgres://econia:econia@postgres:5432/econia"
    depends_on:
      - postgres
    ports:
      - "8085:8085"
