version: "3.9"

services:

  diesel:
    build:
      args:
        DATABASE_URL: "postgres://econia:econia@postgres:5432/econia"
      context: ../../
      dockerfile: src/docker/database/Dockerfile.diesel
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  postgres:
    environment:
      POSTGRES_USER: "econia"
      POSTGRES_PASSWORD: "econia"
    build:
      context: ../../
      dockerfile: src/docker/database/Dockerfile.postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db:
    driver: local
