version: "3.9"

include:
  - compose.dss.yaml

services:
  streamer:
    build:
      context: ../../
      dockerfile: src/docker/tss/Dockerfile
    ports:
      - "50051:50051"
      - "8090:8090"
      - "8080:8080"
      - "8081:8081"

  processor:
    build:
      context: ../../
      dockerfile: src/docker/processor/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8085:8085"
    volumes:
      # Two down from root for GCP disk mounting.
      - "./processor/config.yaml:/config/data/config.yaml"
    environment:
      - HEALTHCHECK_BEFORE_START=true
