services:
  processor-template:
    build:
      context: ../../
      dockerfile: src/docker/processor/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8085:8085"
    volumes:
      # Two down from root for GCP disk mounting.
      - "./processor/config.yaml:/config/data/config.yaml"
