version: "3.9"

include:
  - compose.dss-core.yaml

services:
  streamer:
    build:
      context: ../../
      dockerfile: src/docker/tss/Dockerfile
    ports:
      - "50051:50051"
      - "8090:8090"
      - "8080:8080"
      - "8081:8081"

  processor:
    depends_on:
      - streamer
    environment:
      - HEALTHCHECK_BEFORE_START=true
    extends:
      file: compose.processor-template.yaml
      service: processor-template
