version: '3.9'
services:

  chain:
    build:
      context: ../../
      dockerfile: src/docker/chain/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081

  indexer:
    build:
      context: ../../
      dockerfile: src/docker/indexer/Dockerfile
    depends_on:
      - chain

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=econia
      - POSTGRES_PASSWORD=econia
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local