version: '3.9'
services:

  diesel:
    build:
      context: ../../
      dockerfile: src/docker/database/Dockerfile
      args:
        - DATABASE_URL=postgres://econia:econia@postgres:5432/econia
    depends_on:
      - postgres

  processor:
    build:
      context: ../../
      dockerfile: src/docker/processor/Dockerfile
      args:
        GIT_TAG: abc
        GIT_BRANCH: xyz
        GIT_SHA: qrs
    volumes:
      - /tmp/config.yaml:/config.yaml
    depends_on:
      - postgres
    command: ["-c", "/config.yaml"]

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=econia
      - POSTGRES_PASSWORD=econia
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  postgrest:
    image: postgrest/postgrest
    depends_on:
      - postgres
    environment:
      PGRST_DB_URI: postgres://econia:econia@postgres:5432/econia
      PGRST_DB_ANON_ROLE: postgres
      PGRST_DB_SCHEMA: public
      # You can add other PostgREST configurations here if needed
    ports:
      - "3000:3000"  # Expose PostgREST on port 3000

volumes:
  db:
    driver: local
