# GCP cloud builder config for DSS tutorial on docs site.

images:
  - '${_REPO}/postgres'
  - '${_REPO}/postgrest'

options:
  dynamicSubstitutions: true

steps:

  - id: build-postgres
    args:
      - 'build'
      - '--file'
      - '${_DOCKER_DIR}/database/Dockerfile.postgres'
      - '--tag'
      - '${_REPO}/postgres'
      - '.'
    name: '${_BUILDER}'

  - id: pull-postgrest
    args:
      - 'build'
      - '--file'
      - '${_DOCKER_DIR}/database/Dockerfile.postgrest'
      - '--tag'
      - '${_REPO}/postgrest'
      - '.'
    name: '${_BUILDER}'

substitutions:
  _BUILDER: 'gcr.io/cloud-builders/docker'
  _DOCKER_DIR: 'src/docker'
  _REPO: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/images'
