[package]
name = 'Econia'
version = '2.0.0' # Per SemVer

[addresses]
econia = '0xc0deb00c'
# Mock users for unit tests
user = '0x1234'
user0 = '0x2345'
user1 = '0x3456'
user2 = '0x4567'
user3 = '0x5678'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-framework'
rev = 'a3143756d498821f4f51a5970c7ea35d483938b3'