[package]
name = 'Econia'
version = '4.0.0' # Per SemVer
upgrade_policy = 'compatible'

[addresses]
econia = '0xc0deb00c'
# Mock users for unit tests
user = '0x1234'
user_0 = '0x2345'
user_1 = '0x3456'
user_2 = '0x4567'
user_3 = '0x5678'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-framework'
rev = '9a3687485b2574881eaf2c414024c23fc8ba83ad'