[package]
name = "Econia"
version = "4.1.0"             # Per SemVer.
upgrade_policy = "compatible"

[addresses]
econia = "0xc0de0000fe693e08f668613c502360dc48508197401d2ac1ae79571498cd8b74"
# Mock addresses for testing.
user = "0x1234"
user_0 = "0x2345"
user_1 = "0x3456"
integrator = "0x4567"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
