[package]
name = "EconiaWrapperDemo"
version = '0.2.0'
upgrade_policy = 'compatible'

[addresses]
wrapper_publisher = "_"

[dependencies.Econia]
local = "../econia"

[dev-addresses]
econia = "0xc0de"
wrapper_publisher = "0xace"
