# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli
#
# The db has multiple schemas that need to be tracked here, pending:
# https://github.com/diesel-rs/diesel/pull/3796
# https://github.com/diesel-rs/diesel/issues/1728

[print_schema]
file = "src/schema/public.rs"
custom_type_derives = ["diesel::query_builder::QueryId"]

[migrations_directory]
dir = "migrations"
