name: Rust CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/rust/**"

  pull_request:
    branches: [ "main" ]
    paths:
      - "src/rust/**"

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          ssh-key: ${{ secrets.ECONIA_CI_SSH_PRIVATE_KEY }}

      - uses: rui314/setup-mold@v1

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "rustci"
          shared-key: "ci"
          workspaces: src/rust

      - uses: actions-rs/cargo@v1
        name: Check formatting
        with:
          command: fmt
          args: --check --all --manifest-path src/rust/Cargo.toml

      - uses: actions-rs/cargo@v1
        name: Check
        with:
          command: check
          args: --all-features --all-targets --manifest-path src/rust/Cargo.toml

      - uses: actions-rs/cargo@v1
        name: Clippy
        with:
          command: clippy
          args: --all-features --all-targets --manifest-path src/rust/Cargo.toml

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --all-features --all-targets --manifest-path src/rust/Cargo.toml

      - uses: actions-rs/cargo@v1
        name: Test
        with:
          command: test
          args: --all-features --all-targets --manifest-path src/rust/Cargo.toml
